# .golangci.yml
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosec
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - govet

linters-settings:
  errcheck:
    check-blank: true
  gosec:
    excludes:
      - G104

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - path: server/internal/core/executor/eval/vm/vm\.go
      linters:
        - gosec
      text: "G602|G103"