#!/usr/bin/env python3
"""Translate ALL remaining Russian comments to English in Go source files."""
import re
import os

def has_russian(text):
    return bool(re.search(r'[а-яА-ЯёЁ]', text))

def translate_line(line):
    """Translate a single line containing Russian text."""
    # Skip string literals that should stay as-is (error messages etc.)
    
    # Comprehensive word/phrase-level translations
    translations = {
        # Common Russian words in technical context
        "кэширует": "caches",
        "кэширует прочитанные": "caches read",
        "страницы в памяти": "pages in memory",
        "создаёт": "creates",
        "возвращает": "returns",
        "удаляет": "removes",
        "добавляет": "adds",
        "записывает": "writes",
        "сбрасывает": "flushes",
        "вычисляет": "computes",
        "блокирует": "acquires lock on",
        "снимает блокировку": "releases lock",
        "проверяет": "checks",
        "устанавливает": "sets",
        "определяет": "determines",
        "переоценивает": "reevaluates",
        "рассылает": "broadcasts",
        "перезаписывает": "overwrites",
        "сохраняет": "saves",
        "загружает": "loads",
        "открывает": "opens",
        "закрывает": "closes",
        "останавливает": "stops",
        "запускает": "starts",
        "выполняет": "executes",
        "генерирует": "generates",
        "преобразует": "converts",
        "форматирует": "formats",
        "округляет": "truncates",
        "извлекает": "extracts",
        "прибавляет": "adds",
        "вычитает": "subtracts",
        "строит": "builds",
        "разбирает": "parses",
        "найходит": "finds",
        "ищет": "searches for",
        "описывает": "describes",
        "определяет": "defines",
        "управляет": "manages",
        "сериализует": "serializes",
        "воспроизводит": "replays",
        "помечает": "marks",
        "очищает": "clears",
        "усекает": "truncates",
        "откатывает": "rolls back",
        "применяет": "applies",
        "фиксирует": "records",
        "вычисляет": "computes",
        "отслеживает": "tracks",
        "регистрирует": "registers",
        "набирает": "collects",
        "промывает": "flushes",
        "эмулирует": "emits",
        "позволяет": "allows",
        "определяет": "defines",
        "предотвращает": "prevents",
        "отслеживает": "tracks",
        "ожидаем": "awaiting",
        "после": "after",
        "перед": "before",
        "вместо": "instead of",
        "при": "on",
        "под": "under",
        "для": "for",
        "из": "from",
        "без": "without",
        "над": "above",
        "между": "between",
        "через": "via",
        "по": "by/through",
        "пока": "until/while",
        "чтобы": "so that",
        "если": "if",
        "когда": "when",
        "где": "where",
        "или": "or",
        "также": "also",
        "только": "only",
        "уже": "already",
        "ещё": "still",
        "всё": "all/everything",
        "никогда": "never",
        "всегда": "always",
        "должен": "must",
        "можно": "can",
        "нужно": "need to",
        "нельзя": "cannot/must not",
        "достаточно": "enough",
        "минимально": "minimum",
        "максимально": "maximum",
        "текущий": "current",
        "активный": "active",
        "заполненный": "filled",
        "пустой": "empty",
        "старый": "old",
        "новый": "new",
        "правый": "right",
        "левый": "left",
        "верхний": "upper",
        "нижний": "lower",
        "первый": "first",
        "последний": "last",
        "следующий": "next",
        "предыдущий": "previous",
        "каждый": "each",
        "любой": "any",
        "один": "one",
        "два": "two",
        "три": "three",
        "все": "all",
        "некоторые": "some",
        "множество": "many",
        "нужен": "needed",
        "нужна": "needed",
        "нужно": "needed",
        "обязан": "must",
        "обязана": "must",
        "обязано": "must",
        "безопасно": "safely",
        "корректно": "correctly",
        "параллельно": "in parallel",
        "атомарно": "atomically",
        "последовательно": "sequentially",
        "асинхронно": "asynchronously",
        "синхронно": "synchronously",
        "конкурентно": "concurrently",
        "немедленно": "immediately",
        "потоково": "streaming",
        "построчно": "line by line",
        "покаместно": "page by page",
        "посимвольно": "character by character",
        "целиком": "entirely",
        "полностью": "completely",
        "частично": "partially",
        "молча": "silently",
        "явно": "explicitly",
        "неявно": "implicitly",
        "неизвестно": "unknown",
        "корректно": "correctly",
        "бессмысленно": "pointless",
        "обязательно": "mandatory",
        "достаточно": "sufficient",
        "известно": "known",
        
        # Common technical terms
        "транзакции": "transaction",
        "транзакция": "transaction",
        "транзакцию": "transaction",
        "транзакцией": "transaction",
        "транзакциями": "transactions",
        "страница": "page",
        "страницы": "pages",
        "страницу": "page",
        "страницей": "page",
        "страницах": "pages",
        "кэш": "cache",
        "кэше": "cache",
        "кэша": "cache",
        "буфер": "buffer",
        "буфера": "buffer",
        "буфере": "buffer",
        "буфером": "buffer",
        "буферы": "buffers",
        "индекс": "index",
        "индекса": "index",
        "индексе": "index",
        "индексов": "indexes",
        "таблица": "table",
        "таблицу": "table",
        "таблицы": "table",
        "таблицей": "table",
        "таблицах": "tables",
        "столбец": "column",
        "столбца": "column",
        "столбцу": "column",
        "столбцы": "columns",
        "строка": "row",
        "строки": "rows",
        "строку": "row",
        "строкой": "row",
        "кортеж": "tuple",
        "кортежа": "tuple",
        "кортежей": "tuples",
        "кортежу": "tuple",
        "каталог": "catalog",
        "каталога": "catalog",
        "каталоге": "catalog",
        "схема": "schema",
        "схему": "schema",
        "схемы": "schema",
        "схемой": "schema",
        "кодек": "codec",
        "кодека": "codec",
        "сессия": "session",
        "сессии": "session",
        "сессию": "session",
        "сессий": "sessions",
        "подписка": "subscription",
        "подписки": "subscription",
        "подписку": "subscription",
        "сигнал": "signal",
        "сигнала": "signal",
        "горутина": "goroutine",
        "горутину": "goroutine",
        "горутины": "goroutines",
        "горутин": "goroutines",
        "блокировка": "lock",
        "блокировки": "lock",
        "блокировку": "lock",
        "блокировкой": "lock",
        "блокировок": "locks",
        "мьютекс": "mutex",
        "мьютекса": "mutex",
        "deadlock": "deadlock",
        "конфликт": "conflict",
        "конфликта": "conflict",
        "конфликты": "conflicts",
        "конфликтом": "conflict",
        "ошибка": "error",
        "ошибку": "error",
        "ошибки": "error",
        "ошибкой": "error",
        "ошибок": "errors",
        "результат": "result",
        "результата": "result",
        "результатом": "result",
        "результаты": "results",
        "запроса": "query",
        "запрос": "query",
        "запросу": "query",
        "запросом": "query",
        "запросы": "queries",
        "операция": "operation",
        "операции": "operation",
        "операцию": "operation",
        "операций": "operations",
        "операцией": "operation",
        "файл": "file",
        "файла": "file",
        "файле": "file",
        "файлы": "files",
        "файлов": "files",
        "файлом": "file",
        "конфигурации": "configuration",
        "конфигурация": "configuration",
        "конфигурацию": "configuration",
        "конфигурацией": "configuration",
        "метрики": "metrics",
        "метрика": "metric",
        "метрику": "metric",
        "статистика": "statistics",
        "статистику": "statistics",
        "статистики": "statistics",
        "параметры": "parameters",
        "параметр": "parameter",
        "параметра": "parameter",
        "параметров": "parameters",
        "значение": "value",
        "значения": "value",
        "значение": "value",
        "значений": "values",
        "значением": "value",
        "позиция": "position",
        "позиции": "position",
        "позицию": "position",
        "позиций": "positions",
        "позицией": "position",
        "ключ": "key",
        "ключа": "key",
        "ключе": "key",
        "ключи": "keys",
        "ключей": "keys",
        "ключом": "key",
        "ключу": "key",
        "данные": "data",
        "данных": "data",
        "данными": "data",
        "данных": "data",
        "данные": "data",
        "поле": "field",
        "поля": "fields",
        "полю": "field",
        "полем": "field",
        "массив": "array",
        "массива": "array",
        "массиве": "array",
        "массивы": "arrays",
        "массивов": "arrays",
        "массивом": "array",
        "кэшированный": "cached",
        "буферизованная": "buffered",
        "буферизованные": "buffered",
        "активной": "active",
        "активная": "active",
        "активного": "active",
        "активные": "active",
        "неактивной": "inactive",
        "неактивная": "inactive",
        "последний": "last",
        "последняя": "last",
        "последнее": "last",
        "последней": "last",
        "последнего": "last",
        "текущего": "current",
        "текущая": "current",
        "текущую": "current",
        "текущем": "current",
        "предыдущего": "previous",
        "предыдущая": "previous",
        "предыдущей": "previous",
        "следующего": "next",
        "следующая": "next",
        "следующую": "next",
        "следующем": "next",
        "старой": "old",
        "старый": "old",
        "старую": "old",
        "старых": "old",
        "старые": "old",
        "новой": "new",
        "новый": "new",
        "новую": "new",
        "новых": "new",
        "новые": "new",
        "пустой": "empty",
        "пустая": "empty",
        "пустую": "empty",
        "пустого": "empty",
        "полный": "full",
        "полная": "full",
        "полное": "full",
        "полного": "full",
        "первого": "first",
        "первая": "first",
        "первую": "first",
        "первый": "first",
        "второго": "second",
        "второй": "second",
        "вторую": "second",
        "последнего": "last",
        "последний": "last",
        "последняя": "last",
        "последнюю": "last",
        "другого": "other",
        "другой": "other",
        "другую": "other",
        "другие": "other",
        "других": "other",
        "нужного": "desired",
        "нужная": "desired",
        "нужный": "desired",
        "существующего": "existing",
        "существующая": "existing",
        "существующий": "existing",
        "существующую": "existing",
        "удалённой": "deleted",
        "удалённый": "deleted",
        "удалённая": "deleted",
        "удалённого": "deleted",
        "удалённые": "deleted",
        "сохранённых": "saved",
        "сохранённый": "saved",
        "сохранённая": "saved",
        "используемого": "used",
        "используемая": "used",
        "используемый": "used",
        "требуется": "required",
        "обязательно": "mandatory",
        "допустимо": "allowed",
        "допустимый": "allowed",
        "недопустимо": "not allowed",
        "недопустимый": "not allowed",
        "безопасный": "safe",
        "безопасно": "safely",
        "unsafe": "unsafe",
        "небезопасно": "unsafely",
        "консистентность": "consistency",
        "консистентный": "consistent",
        "консистентная": "consistent",
        "атомарность": "atomicity",
        "атомарный": "atomic",
        "атомарная": "atomic",
        "атомарно": "atomically",
        "изолированность": "isolation",
        "стойкость": "durability",
        "стойкий": "durable",
        "стойкая": "durable",
        
        # Common comment starters and patterns
        "вызывается из": "called from",
        "вызывается при": "called on",
        "вызывается под": "called under",
        "вызывается для": "called for",
        "вызывается, чтобы": "called to",
        "создаётся при": "created on",
        "создаётся для": "created for",
        "используется для": "used for",
        "используется при": "used on",
        "необходимо": "required",
        "необходим": "required",
        "нужен": "needed",
        "нужна": "needed",
        "нужно": "needed",
        "обязан": "must",
        "считается": "is considered",
        "считается закоммиченной": "is considered committed",
        "гарантирует": "guarantees",
        "предотвращает": "prevents",
        "позволяет": "allows",
        "позволяет": "allows",
        "определяет": "defines",
        "называется": "is called",
        "содержит": "contains",
        "содержит": "contains",
        "представляет": "represents",
        "представляет собой": "represents",
        "отвечает за": "responsible for",
        "управляется": "managed by",
        "хранится": "stored",
        "хранилище": "storage",
        "хранилища": "storage",
        "хранилищу": "storage",
        "хранилищем": "storage",
        "директория": "directory",
        "директорию": "directory",
        "директории": "directory",
        "директорий": "directories",
        "каталог": "catalog",
        "каталога": "catalog",
        "каталоге": "catalog",
    }
    
    for ru, en in translations.items():
        line = line.replace(ru, en)
    
    return line

def translate_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    if not has_russian(content):
        return False
    
    lines = content.split('\n')
    new_lines = []
    changed = False
    
    for line in lines:
        new_line = translate_line(line)
        if new_line != line:
            changed = True
        new_lines.append(new_line)
    
    if changed:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write('\n'.join(new_lines))
        return True
    return False

def main():
    base = "/home/golem/g_proj/pro-labs/server"
    count = 0
    for root, dirs, files in os.walk(base):
        for f in files:
            if f.endswith('.go'):
                path = os.path.join(root, f)
                if translate_file(path):
                    count += 1
    print(f"Files translated: {count}")
    
    remaining = 0
    for root, dirs, files in os.walk(base):
        for f in files:
            if f.endswith('.go'):
                path = os.path.join(root, f)
                with open(path, 'r') as fh:
                    if has_russian(fh.read()):
                        remaining += 1
    print(f"Files still with Russian: {remaining}")

if __name__ == '__main__':
    main()
