package main

import (
	"crypto/tls"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"
)

func runHealthCheck(monitorPort int) int {
	url := fmt.Sprintf("http://127.0.0.1:%d/health", monitorPort)
	client := &http.Client{
		Timeout: 3 * time.Second,
		Transport: &http.Transport{
			// Health check always targets localhost — TLS verification is unnecessary
			// and would fail with self-signed certs generated by the server.
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true}, // #nosec G402 — localhost only
		},
	}

	resp, err := client.Get(url)
	if err != nil {
		// Try HTTPS if HTTP fails (TLS might be enabled)
		httpsURL := fmt.Sprintf("https://127.0.0.1:%d/health", monitorPort)
		resp, err = client.Get(httpsURL)
		if err != nil {
			fmt.Fprintf(os.Stderr, "health check failed: %v\n", err)
			return 1
		}
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		fmt.Fprintf(os.Stderr, "health check failed: status=%d body=%s\n", resp.StatusCode, string(body))
		return 1
	}
	return 0
}

func envBool(name string, fallback bool) bool {
	value := strings.TrimSpace(strings.ToLower(os.Getenv(name)))
	if value == "" {
		return fallback
	}
	switch value {
	case "1", "true", "yes", "on":
		return true
	case "0", "false", "no", "off":
		return false
	default:
		return fallback
	}
}
