name: Semgrep
on: pull_request
jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run semgrep
        run: |
          pip install semgrep
          semgrep --config .semgrep/ --error ./server
